"""empty message

Revision ID: e39154b5f1df
Revises: 6203577c80df
Create Date: 2021-09-18 16:19:45.467890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e39154b5f1df'
down_revision = '6203577c80df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_in_movie',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id')
    )
    op.drop_table('projects')
    op.drop_table('assignments')
    op.drop_table('reviewers')
    op.add_column('actors', sa.Column('full_name', sa.String(length=512), nullable=False))
    op.add_column('actors', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.drop_constraint('actors_name_key', 'actors', type_='unique')
    op.drop_column('actors', 'gender')
    op.drop_column('actors', 'age')
    op.add_column('movies', sa.Column('release_year', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('imdb_rating', sa.Float(), nullable=False))
    op.drop_constraint('movies_title_key', 'movies', type_='unique')
    op.drop_column('movies', 'release_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint('movies_title_key', 'movies', ['title'])
    op.drop_column('movies', 'imdb_rating')
    op.drop_column('movies', 'duration')
    op.drop_column('movies', 'release_year')
    op.add_column('actors', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('actors', sa.Column('gender', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.create_unique_constraint('actors_name_key', 'actors', ['name'])
    op.drop_column('actors', 'date_of_birth')
    op.drop_column('actors', 'full_name')
    op.create_table('reviewers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('reviewers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reviewers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reviewer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='assignments_project_id_fkey'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], name='assignments_reviewer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assignments_pkey')
    )
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='projects_pkey')
    )
    op.drop_table('actor_in_movie')
    # ### end Alembic commands ###
